### PR TITLE
Add Cypress for integration/e2e testing

### PR DESCRIPTION
**Pull request by designorant**
This also includes two scenarios used in real User Testing.

### CODE REVIEW

**Comment by designorant** [comment]
Phew, runs at last: https://app.netlify.com/sites/ons-data-map/deploys/62176b554f691e0008a4bf55#L324

**Comment by designorant** [comment]
Story time (not really, just need help).

During one of the user sessions there was a case of a missing map, an issue that we couldn't replicate ourselves no matter what. It's been hanging on Trello since: https://trello.com/c/OFhWF7Mv/273-bug-missing-map-on-mobile-view

Eventually I decided to automate the user journey hoping the issue would crop out eventually, so the test goes as this PR shows:

```js
beforeEach(() => {
  cy.visit("/");
  cy.wait(500);
});

describe("User Testing Scenarios", () => {
  it("can go through Route 1", () => {
    cy.contains("Choose a category").click();
    cy.wait(500);
    cy.url().should("include", "/categories");
    cy.contains("Education").should("exist");
    cy.contains("Health").should("exist");
    cy.contains("Housing").should("exist");
    cy.contains("Identity").should("exist");
    cy.contains("Population").should("exist");
    cy.contains("Work").should("exist");
    cy.contains("Housing").click();
    cy.contains("Show Heating options").click();
    cy.contains("Gas").click();
    cy.wait(500);
    cy.url().should("include", "/housing/heating/gas");
    cy.get(".mapboxgl-canvas").should("be.visible");
  });
});
```

Cypress waits 500ms after each route change, check for elements, and clicks through to a page where the error occurred.

Here's the interesting bit:

These tests pass and fail randomly, regardless of the delay and often way before the test is concerned about the map. I've tried with anything up to 4000ms all giving out random errors that related to a map:

```sh
TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
> Cannot read property 'remove' of null
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
```
or
```sh
> Cannot read properties of undefined (reading 'getSource')
```

There seems to be something wrong with the way we load the map that causes these errors and likely the error that one of the users came across during the real testing. They don't seem to pop up during manual testing for me, and I get more positive results when running Cypress locally, byt Cypress on Netlify fails [_almost_](https://app.netlify.com/teams/thomasridd/builds/62176b554f691e0008a4bf55#L324) constantly.

**Comment by designorant** [comment]
Phew, this builds now: https://app.netlify.com/sites/ons-data-map/deploys/6218bbdfce9e080007af760c

**Review by James-Nitron — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
