### PR TITLE
Display statistical figures

### PR DESCRIPTION
**Pull request by designorant**
Raising this on behalf of @patrickjfl and @vmilitaru. The original plan was to me to work on this branch and add CSS here but I need actually need to merge this in `feature/category-selector-and-map-key` hence raising it separately.

### CODE REVIEW

**Comment by designorant** [comment]
LGTM :-P

**Comment by designorant** [comment]
Turns out I cannot approve a PR raised by myself even though it's not my work. Bummer.

**Comment by designorant** [comment]
Actually, just for the record: LGTM, @patrickjfl @vmilitaru please approve.

**Review by vmilitaru — APPROVED** [review]
Code reviewed and approved by @designorant

**Pull request merged**
