### PR TITLE
Add devex utils

### PR DESCRIPTION
**Pull request by designorant**
Added a ton of configs and ran `npm run format` now that we've got a unified repo.

None of this is enforced in the tooling. It's on us to have Prettier, ESLint and ideally a Svelte editor plugins installed, but there's always `npm run lint` and `npm run format` available anyway.

Fixed `ONSSelect` along the way too.

### CODE REVIEW

**Review by patrickjfl — APPROVED** [review]
Nice one Michal

**Comment by designorant** [comment]
So... this breaks Storybook, `"type": "module"` [in particular](https://github.com/storybookjs/storybook/issues/11587).

Gave up on it last night. We may end up moving to SvelteKit as that's where everything moves to in the Svelte land, but no way we can do that for this sprint.

**Comment by designorant** [comment]
Rebased on `master`.

**Comment by designorant** [comment]
@vmilitaru @patrickjfl Cleaned it up to leave just the config files in place. Safe to merge to `master` and into other branches.

**Review by patrickjfl — APPROVED** [review]

**Comment by designorant** [comment]
Gracias!

**Pull request merged**
