### PR TITLE
Feature/use census data component

### PR DESCRIPTION
**Pull request by thomasridd**
image

### CODE REVIEW

**Comment by vmilitaru** [comment]
Tom, the UseCensusData component file is empty, is this PR only for the ONSSkipLink component?

**Comment by thomasridd** [comment]
Good catch @vmilitaru 
I hadn't pushed properly
I've also reformatted

**Review by vmilitaru — APPROVED** [review]
👍

**Review by designorant — APPROVED** [review]
LGTM! Nice pull out of the Skip Link!

**Pull request merged**
