### PR TITLE
Updates the CensusTableByLocation component - ticket#362

### PR DESCRIPTION
**Pull request by vmilitaru**
**What**

Updates the `<CensusTableByLocation />` component to meet the V4 Design and removes the horizontal scroll bar from the `<BasePage />` component. 

Screenshot 2022-03-03 at 10 51 11

Screenshot 2022-03-10 at 12 58 06

### CODE REVIEW

**Review by designorant — APPROVED** [review]
🚀

**Review by PeteMontgomery — APPROVED** [review]
It works as designed 👍

**Comment by vmilitaru** [comment]
signed off by design

**Review by PeteMontgomery — APPROVED** [review]

**Review by designorant — APPROVED** [review]
🚀

**Pull request merged**
